<?php
?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Testing password</title>
</head>
<body>
<form action="decrypt_password.php">
    <fieldset>
        <label for="password">Mot de passe</label>
        <input type="password" name="password"/>
    </fieldset>
    <fieldset>
        <label for="hash">Hash</label>
        <input type="password" name="hash"/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Envoyer"/>
    </fieldset>
</form>
</body>
</html>
