<?php



?>

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Testing password</title>
</head>
<body>
<form action="decrypt_password.php" method="post">
    <fieldset>
        <label for="password">Veuillez entrer votre password: </label>
        <input type="password" name="password" id="password">
    </fieldset>
    <fieldset>
        <button type="submit">C'est parti pour le hashage~!!</button>
    </fieldset>
</form>
</body>
</html>
