<?php
if (isset($_SESSION["user"], $_SESSION["user"]["first_name"], $_SESSION["user"]["last_name"] )) {
    echo "<h1>Bonjour" . " " . $_SESSION["user"]["first_name"] . " " . $_SESSION["user"]["last_name"] . "</h1>";
}?>

<!--Vu que l'on est require dans le layout, il ne faut pas mettre les balises html. Elles sont deja dans le layout-->

<a href="index.php?route=inscription">Inscription</a>
<a href="index.php?route=connexion">Connexion</a>